USE [master]
GO

/****** Object:  Database [u_kluczews]    Script Date: 10.12.2022 15:42:03 ******/
CREATE DATABASE [u_kluczews]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'u_kluczews', FILENAME = N'/var/opt/mssql/data/u_kluczews.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'u_kluczews_log', FILENAME = N'/var/opt/mssql/data/u_kluczews_log.ldf' , SIZE = 66048KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [u_kluczews].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [u_kluczews] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [u_kluczews] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [u_kluczews] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [u_kluczews] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [u_kluczews] SET ARITHABORT OFF 
GO

ALTER DATABASE [u_kluczews] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [u_kluczews] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [u_kluczews] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [u_kluczews] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [u_kluczews] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [u_kluczews] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [u_kluczews] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [u_kluczews] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [u_kluczews] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [u_kluczews] SET  ENABLE_BROKER 
GO

ALTER DATABASE [u_kluczews] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [u_kluczews] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [u_kluczews] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [u_kluczews] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [u_kluczews] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [u_kluczews] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [u_kluczews] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [u_kluczews] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [u_kluczews] SET  MULTI_USER 
GO

ALTER DATABASE [u_kluczews] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [u_kluczews] SET DB_CHAINING OFF 
GO

ALTER DATABASE [u_kluczews] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [u_kluczews] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [u_kluczews] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [u_kluczews] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [u_kluczews] SET QUERY_STORE = OFF
GO

ALTER DATABASE [u_kluczews] SET  READ_WRITE 
GO

